# include <stdlib.h>
# include <stdio.h>
# include <math.h>
# include <time.h>
# include <omp.h>
 
extern double angle;
extern double sigma;
extern double startx;
extern double endx;
extern double starty;
extern double endy;
extern double thickness;
extern double hgthickness;
extern double pthickness;
extern double radius;
extern int nx;
extern int ny;
extern int nm;
extern int ncount[];
extern double epo;
extern double epi;
extern double ewu;
extern double ewb;
extern double emhu;
extern double emhb;
extern double emt;
extern double qp;
extern double F;
extern double T;
extern double Kb;
extern double KbT;
extern double RT;
extern double ec;
extern double h;
extern double hx;
extern double hy;
extern double slu;
extern double slb;
extern int drepeat;
extern int qrepeat;
extern int prepeat;
extern int nbkup ;
extern int nbkbt ;
extern int nmemu ;
extern int nmemb ;
extern double zbkup[];
extern double cbkup[];
extern double cbkupM[];
extern double zbkbt[];
extern double cbkbt[];
extern double cbkbtM[];
extern double zmemu[];
extern double cmemu[];
extern double cmemuM[];
extern double zmemb[];
extern double cmemb[];
extern double cmembM[];
extern double pbfactor;
extern double EnergyTot;
extern double EnergyBen;
extern double EnergyBenwosigma;
extern double EnergyEle;
extern double EnergyEleflat;
extern double kappa;
extern double memarea;
extern int id0;
extern int id1;
extern int id2;
extern int id3;
extern int id4;
extern int id5;
extern int id6;
extern int id7;
extern int id8;
extern int id9;
extern int isMem;
extern int isNP;
extern int isPlot;
extern int isFd2d;
extern int isclean;
extern int isPrint;
extern int pot2d;
extern double memfactor;
extern double memshift;
extern double parshift;
extern clock_t times;
extern FILE *errorfile;
extern double jacobfact;
//extern double v0;
//extern double v1;
extern int status;

double electricfield(double efieldr[],double efieldz[],double pot[],double temp[]);
double freeenergy(double pot[],double qregion[],int region[],double xvec[],double pot0[]);
double debye();
double lambda(int region,int i);
void addrhs(double acc[],int icc[],int ccc[],double rhs[],double inguess[],int count,int n,int region[],double qregion[],double pot0[]);
void init ( double x[], double y[],	int n, double a[],int b[],int c[], double rhs[] ,double height [],double dregion[],int region[]);
double d ( int nr);
double f ( int nr,double v,double v0);
double ff( int nr,double v,double v0);
void jacobian ( int n, double acc[],int icc[],int ccc[] ,int count,double inguess[],int region[],double pot0[]);
void smooth ( int rep,double dregion [],double temp[]);
void smoothq ( int rep,double dregion [],double temp[]);
void r8sp_mv ( int m, int n, int nz_num, int row[], int col[],   double a[], double x[] , double b[]);